import './globals.css'
import type { Metadata } from 'next'
import { IBM_Plex_Mono, Inter } from 'next/font/google'
import Navbar from './components/navigation/navbar'

const ibm = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: '400'
})
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ibm.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
